### PR TITLE
Add generator files to the Build output

### PR DESCRIPTION
**Pull request by dgkanatsios**
This PR adds the JSON settings generator files to the output. FYI @pgilmorepf @jordan-playfab 
Also setting a checkbox that configures required values set to checked as default

### CODE REVIEW

**Review by emmayspark — APPROVED** [review]

**Comment by pgilmorepf** [comment]
Addin @jordan-playfab, as I recall there being more files in his updated version, and I'm not sure how it interacts with VS (his readme instructions don't reflect any interaction with VS).

**Comment by dgkanatsios** [comment]
FWIW, adding the html/js/css files in the csproj in this PR didn’t work in getting them as output during publishing <sigh>
something broke in dotnet publish command after .NET Core 3.1

**Comment by pgilmorepf** [comment]
That's kinda what I suspected. That webpage just isn't designed to be integrated into that sln.

**Comment by dgkanatsios** [comment]
Webpage with the files included (the two CSS and the one js) works just fine with “dotnet build” command, the problem is with “dotnet publish”.

**Pull request merged**
